In [7]:
my_dict = {'a':'choi', 'b':'take', 'c':'right'}

inverse_dict = {}

for k, v in my_dict.items():
    inverse_dict[v] = k

print(inverse_dict)

{'choi': 'a', 'take': 'b', 'right': 'c'}


In [8]:
my_dict = {'a':'choi', 'b':'take', 'c':'right'}

inverse_dict = {}

for k in my_dict:
    inverse_dict[my_dict[k]] = k

print(inverse_dict)

{'choi': 'a', 'take': 'b', 'right': 'c'}


In [37]:
import random

answer = []

for i in range(1, 10001):
    k = random.randrange(1, 6)
    answer.append(k)

len(answer)
print(answer)

, 3, 1, 2, 2, 5, 3, 4, 2, 2, 5, 1, 1, 3, 4, 1, 1, 2, 5, 4, 3, 3, 4, 2, 2, 1, 5, 4, 4, 3, 1, 3, 3, 4, 1, 3, 3, 1, 2, 5, 2, 3, 5, 3, 1, 5, 3, 4, 1, 4, 4, 4, 5, 1, 3, 4, 5, 3, 2, 2, 5, 4, 1, 1, 2, 1, 5, 4, 1, 5, 1, 3, 2, 2, 4, 4, 1, 5, 4, 2, 1, 4, 3, 2, 5, 2, 3, 1, 2, 3, 3, 1, 2, 3, 2, 4, 4, 4, 1, 1, 2, 2, 4, 1, 5, 1, 2, 1, 4, 4, 5, 3, 3, 3, 1, 1, 1, 1, 5, 3, 3, 5, 4, 2, 2, 3, 3, 2, 1, 3, 5, 3, 2, 1, 2, 4, 4, 4, 3, 5, 4, 3, 5, 5, 4, 4, 3, 2, 1, 1, 4, 1, 5, 2, 4, 2, 5, 1, 3, 1, 5, 5, 3, 4, 4, 4, 2, 1, 4, 4, 1, 3, 1, 5, 1, 3, 3, 3, 2, 4, 1, 2, 1, 1, 4, 4, 2, 2, 2, 4, 3, 3, 2, 3, 4, 5, 5, 1, 4, 1, 1, 4, 5, 5, 3, 1, 5, 2, 4, 3, 1, 1, 4, 1, 4, 3, 5, 1, 5, 3, 4, 5, 1, 3, 4, 2, 2, 5, 4, 1, 1, 4, 3, 2, 5, 5, 1, 2, 1, 1, 2, 2, 3, 3, 1, 2, 1, 1, 2, 1, 1, 2, 1, 3, 3, 5, 3, 3, 1, 1, 4, 4, 4, 3, 3, 3, 2, 3, 2, 5, 1, 1, 5, 1, 3, 5, 3, 5, 2, 1, 5, 2, 4, 1, 2, 2, 2, 4, 2, 1, 3, 3, 5, 5, 3, 2, 4, 5, 2, 3, 1, 1, 1, 5, 4, 5, 2, 5, 1, 4, 2, 5, 4, 2, 4, 3, 1, 3, 2, 4, 3, 5, 3, 4, 1, 2, 4, 1, 1, 3, 4, 5, 1, 3,

In [44]:
a = [1, 2, 3, 4, 5]
b = [3, 3, 1, 1, 2, 2, 4, 4, 5, 5]

soopo_1 = []
soopo_2 = []
soopo_3 = []

for i in range(1, 2001):
    for k in range(0, 5):
     soopo_1.append(a[k])


for i in range(1, 10001):
    k = random.randrange(1, 6)
    soopo_2.append(k)


for i in range(1, 1001):
    for k in range(0, 10):
     soopo_1.append(b[k])


, 1, 4, 4, 2, 1, 3, 4, 4, 5, 5, 4, 5, 2, 5, 4, 1, 1, 4, 4, 4, 4, 1, 3, 4, 3, 2, 3, 4, 5, 5, 3, 2, 1, 5, 5, 5, 4, 2, 3, 4, 4, 2, 1, 1, 5, 5, 5, 3, 3, 4, 4, 1, 5, 4, 4, 4, 1, 4, 5, 2, 2, 3, 5, 1, 3, 4, 4, 3, 3, 4, 4, 4, 2, 2, 1, 4, 1, 2, 4, 1, 5, 4, 4, 5, 2, 4, 3, 5, 3, 2, 2, 3, 5, 5, 4, 3, 3, 2, 5, 2, 2, 2, 1, 4, 4, 1, 2, 5, 5, 2, 2, 4, 1, 1, 1, 1, 3, 4, 5, 4, 1, 4, 2, 3, 5, 2, 5, 2, 4, 3, 1, 2, 3, 2, 5, 4, 1, 3, 2, 3, 5, 2, 1, 1, 2, 5, 3, 5, 4, 1, 1, 2, 2, 1, 5, 4, 5, 2, 3, 1, 2, 4, 2, 5, 5, 2, 2, 4, 4, 3, 1, 3, 4, 5, 4, 5, 4, 1, 4, 5, 1, 5, 4, 5, 5, 4, 3, 1, 5, 3, 1, 2, 4, 5, 3, 5, 3, 3, 1, 2, 5, 3, 4, 2, 1, 1, 1, 4, 1, 2, 1, 2, 5, 3, 5, 4, 3, 2, 2, 2, 1, 3, 4, 1, 5, 4, 1, 2, 1, 4, 3, 4, 1, 2, 1, 4, 2, 5, 5, 5, 2, 4, 5, 5, 3, 2, 4, 1, 3, 3, 5, 4, 1, 3, 4, 2, 3, 5, 2, 4, 1, 3, 3, 5, 2, 4, 2, 3, 2, 1, 2, 2, 1, 4, 4, 5, 4, 2, 3, 1, 1, 4, 4, 5, 3, 5, 5, 4, 4, 4, 1, 1, 5, 3, 1, 2, 4, 3, 4, 5, 5, 2, 5, 3, 1, 4, 5, 2, 5, 3, 1, 1, 5, 1, 5, 5, 2, 5, 1, 5, 4, 4, 5, 2, 1, 3, 4, 4, 5, 5, 1, 2, 3,

In [55]:
s_1 = 10
s_2 = 11
s_3 = 11

a = {s_1:1, s_2:2, s_3:3}

max(a)

11

In [56]:
a = []
a.pop()

IndexError: pop from empty list

borad 는 array
moves 는 리스트로

In [66]:
a = [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
b = []

b.append(a[0].pop())
print(a)
print(b)


[[1, 2], [1, 2, 3], [1, 2, 3]]
[3]


In [67]:
c = [1, 2, 3]
c[-1]

3

In [135]:
def solution(board, moves):
    
    bucket = []
    answer = 0

    for i in moves:
        while board[i-1].count(0) != 0:
            board[i-1].remove(0)

    print(board)
    
    for i in moves:
        try:
            doll = board[i-1].pop()        
            bucket.append(doll)
        except:
            continue
        finally:
            print(bucket)

        if len(bucket) < 2:
            continue
        
        elif bucket[len(bucket)-2] == bucket[len(bucket)-1]:
                bucket.pop()
                bucket.pop()
                answer += 2
        else:
            continue
            
    return answer


solution([[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]], [1,5,3,5,1,2,1,4])


[[], [1, 3], [2, 5, 1], [4, 2, 4, 4, 2], [3, 5, 1, 3, 1]]
[]
[1]
[1, 1]
[3]
[3]
[3, 3]
[]
[2]


4

In [138]:
def solution(board, moves):
    
    bucket = []
    answer = 0

    for i in moves:
        while board[i-1].count(0) != 0:
            board[i-1].remove(0)

    print(board)
    
    for i in moves:
        try:
            doll = board[i-1].pop()        
            bucket.append(doll)
        except:
            continue
        finally:
            print(bucket)

        if len(bucket) < 2:
            continue
        
        elif bucket[len(bucket)-2] == bucket[len(bucket)-1]:
                bucket.pop()
                bucket.pop()
                answer += 2
        else:
            continue
            
    return answer

solution([[0, 2, 0], [1, 2, 0], [2, 2, 1]],[1, 2, 2, 2, 1, 3] )

[[2], [1, 2], [2, 2, 1]]
[2]
[2, 2]
[1]
[1]
[1]
[1, 1]


4

In [117]:
board = [1, 2, 4, 0, 0, 5, 6, 0]


for i in range(board.count(0)):
    board.remove(0)

print(board)

[1, 2, 4, 5, 6]


In [109]:
board = [1, 2, 4, 0, 0, 5, 6, 0]
board[len(board)-1]

0

In [110]:
for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [130]:
board = [1, 2, 4, 0, 0, 5, 6, 0]

board.remove(0)
board.remove(0)
board.remove(0)

board

[1, 2, 4, 5, 6]

In [ ]:
board = [[0,2,0],[1,2,0],[2,2,1]]

moves = [1,2,2,2,1,3]

In [201]:
import random

def solution(numbers):
    answer = []
    tmp = []

    for i in range(len(numbers)):
        for k in range(i+1, len(numbers)):
            tmp.append(numbers[i] + numbers[k])
    
    a = set(tmp)
    answer = list(a)
    answer.sort()


    return answer

leng = random.randrange(2, 101)

test_list = []

for i in range(leng):
    num = random.randrange(0, 101)
    test_list.append(num)

solution(test_list)

[8,
 14,
 24,
 30,
 34,
 36,
 40,
 42,
 45,
 50,
 51,
 52,
 61,
 62,
 71,
 73,
 74,
 80,
 81,
 83,
 84,
 87,
 89,
 90,
 97,
 99,
 100,
 102,
 104,
 107,
 108,
 109,
 110,
 111,
 112,
 118,
 120,
 121,
 128,
 130,
 132,
 139,
 141,
 147,
 149,
 150,
 156,
 157,
 159,
 168,
 170,
 175,
 177,
 178,
 179,
 180,
 198,
 200]

In [203]:
a = [1, 2, 3, 3, 3]

a.count(1)

1

In [207]:
def solution(participant, completion):
    answer = ''
    for i in participant:
        if completion.count(i) != 0:
            completion.remove(i)
        else:
            answer = i
            break

    return answer

solution(	["mislav", "stanko", "mislav", "ana"], ["stanko", "ana", "mislav"])

'mislav'

In [ ]:
def solution(participant, completion):
    for i in participant:
        try:
            completion.remove(i)
        except:
            answer = i
            break
    return answer

In [208]:
def solution(participant, completion):
    answer = ''
    dict1 = {}
    for p in participant:
        if p not in dict1:
            dict1[p] = 0
        if p in dict1:
            dict1[p] = dict1.get(p) + 1
    for c in completion:
        dict1[c] = dict1.get(c)-1
    for p in participant:
        if dict1[p] == 1:
            answer = p
    return answer

solution(	["mislav", "stanko", "mislav", "ana"], ["stanko", "ana", "mislav"])

'mislav'

In [209]:
def solution(participant, completion):
    a = int(len(participant)/2)
    b = len(participant)
    for i in range(0, a):
        try:
            completion.remove(participant[i])
        except:
            try:
                for i in range(a+1, b):
                    completion.remove(participant[i])
            except:
                answer = participant[i]
                break
    return answer

solution(["mislav", "stanko", "mislav", "ana"], ["stanko", "ana", "mislav"])

UnboundLocalError: local variable 'answer' referenced before assignment

In [10]:
def solution(array, commands):
    answer = []

    for i in commands:
        tmp = array[i[0] - 1: i[1]]
        tmp.sort()
        answer.append(tmp[i[2] - 1])


    return answer

In [9]:
a = [1, 5, 2, 6, 3, 7, 4]	
p = a[2:6]
p.sort()
print(p)

[2, 3, 6, 7]


In [14]:
from datetime import date

def solution(a, b):
    answer = date(2016,a,b).strftime('%a').upper()
    return answer

In [ ]:
def solution(arr):
    answer = []
    count = 0

    for i in arr:

        if count == 1:
            if i == j:
                j = i
                pass
            else:
                answer.append(i)
                j = i
            
        else:
            j = i
            answer.append(i)
            count += 1
            pass

    return answer

In [30]:
def solution(arr, divisor):
    answer = []
    for i in arr:
        if (i % divisor) == 0:
            answer.append(i)
        else:
            pass
    
    if answer == []:
        answer.append(-1)


    answer.sort()
    return answer

solution([3, 2, 6], 10)

[-1]

In [28]:
a = []

if a:
    print("t")
else:
    print('f')

f


In [26]:
a = [-1]
a.sort()
print(a)

[-1]


In [ ]:
def solution(s):
    answer = ''
    if len(s) % 2 == 0:
        answer = (s[int(len(s) / 2) - 1 : int(len(s) / 2) + 1])
    else:
        answer = (s[int(len(s) / 2)])



    return answer

In [45]:
s = '123456789'
int(len(s) / 2)

s[int(len(s) / 2)]

#s[int(len(s) / 2) - 1 : int(len(s) / 2) + 1]

'5'

In [ ]:
def solution(a, b):
    answer = 0

    tmp = []
    tmp.append(a)
    tmp.append(b)
    tmp.sort()

    for i in range(tmp[0], tmp[1]+1):
        answer += i

    return answer

In [47]:
a = 0

for i in range(1, 11):
    a += i

print(a)


55


In [49]:
a = ['acd', 'abc']
a.sort()
print(a)

['abc', 'acd']


In [75]:
def solution(strings, n):
    answer = []
    tmp = []
    tmp_2 = []
    count = 0

    strings.sort()

    for i in strings:
        count += 1
        tmp.append((i[n], count))
        tmp_2.append((i, count))

    tmp.sort()

    
    print(tmp)
    print(tmp_2)


    return answer

solution(["abce", "abcd", "cdx"], 2)

[('c', 1), ('c', 2), ('x', 3)]
[('abcd', 1), ('abce', 2), ('cdx', 3)]


[]

In [60]:
my_dict = {}

my_dict[1] = 12
my_dict[2] = 11
my_dict[3] = 10

print(my_dict)

{1: 12, 2: 11, 3: 10}


In [64]:
import operator
sorted(my_dict, key = operator.itemgetter(0))

TypeError: 'int' object is not subscriptable

In [67]:
a = (1, 3)
b = (2, 2)
c = (3, 1)

qw = [c, b, a]
qw.sort()

print(qw)

[(1, 3), (2, 2), (3, 1)]


In [ ]:
strings = ['asd']


answer = []
tmp = []
count = 0

for i in strings:
    count += 1
    tmp.append((i[n], count))

In [73]:
a = [(1, 2), (2, 3), (4, 5)]

a[1][0]

2

In [77]:
def solution(strings, n):
    return sorted(sorted(strings), key=lambda strings: strings[n])

In [3]:
def solution(a, b):
    answer = 0
    count = 0
    while True:
        
        answer += (a[count] * b[count])
        
        count += 1
        if count == len(a):
            break
    return answer

solution([1,2,3,4]	, [-3,-1,0,2])

3

In [13]:
chk = [ord('a'), ord('z'), ord('A'), ord('Z')]
chk


[97, 122, 65, 90]

In [20]:
def solution(s, n):
    answer = ''

    tmp = list(s)
    for i in tmp:
        if 97 <= ord(i) <= 122:
            if ord(i) + n <= 122:
                answer = answer + chr(ord(i) + n)
            
            elif ord(i) + n > 122:
                answer = answer + chr(ord(i) + n - 26)

        elif 65 <= ord(i) <= 90:
            if ord(i) + n <= 90:
                answer = answer + chr(ord(i) + n)
            elif ord(i) + n > 90:
                answer = answer + chr(ord(i) + n - 26)
        else:
            answer = answer + i

    return answer
        
solution ('AaZz', 25)

'ZzYy'

In [12]:
ord('z') + 1 -26

97

In [13]:
90-65

25

In [61]:
def solution(s):
    answer = ''
    answer_tmp = ''
    tmp = s.split(" ")
    
    for i in tmp:
        count = 0
        answer_tmp = ''

        for j in i:
            if i == "":
                continue
            elif i.isalpha():
                if count % 2 == 0:
                    answer_tmp = answer_tmp + j.upper()
                else:
                    answer_tmp = answer_tmp + j.lower()

            count += 1
        answer = answer + answer_tmp + " "
        
    answer = answer.rstrip(" ")
    return answer

solution('try hello world')

'TrY HeLlO WoRlD'

In [56]:
a = "try    hello      world"
b = a.split(" ")
b


['try', '', '', '', 'hello', '', '', '', '', '', 'world']

In [43]:
a.rstrip(" ")

'try hello world'

In [55]:
a = "A"
a.upper()

'A'

In [59]:
a = "a"
b = "B"
b.isalpha()

True

In [69]:
def solution(n):
    answer = ""
    tmp = []
    n = str(n)
    for i in n:
        tmp.append(i)
    tmp.sort()
    tmp.reverse()

    for i in tmp:
        answer = answer + i
    
    answer = int(answer)
    return answer

solution(123)

321

In [105]:
from math import * 

def solution(n):
    answer = -1
    if sqrt(n) / int(sqrt(n)) == 1.0:
        answer = (sqrt(n) + 1) * (sqrt(n) + 1)

    return answer

solution(144)

169.0

In [92]:
import math
a= math.sqrt(25)
print(a)


type(a) == int


5.0


False

In [99]:
import math
a = 9
b = int(math.sqrt(9))

b / math.sqrt(a)

1.0

In [102]:
(5 / 5.0) ^2

TypeError: unsupported operand type(s) for ^: 'float' and 'int'

In [123]:
def solution(arr):
    m = min(arr)
    answer = []
    answer = arr.remove(m)
    if answer == []:
        answer = [-1]

    return answer

solution([4, 3, 2, 1])

In [111]:
arr = [1, 2, 3,4, 5]
arr = arr.remove(min(arr))
arr

In [113]:
arr = [1, 2, 3,4, 5]
m = min(arr)
arr.remove(m)
arr

[2, 3, 4, 5]

In [127]:
def solution(arr):
    m = min(arr)
    arr.remove(m)
    if arr == []:
        arr = [-1]

    return arr

solution([4])

[-1]

In [ ]:
def solution(num):
    answer = ''
    if num % 2 == 0:
        answer = "Even"
    else:
        answer = "Odd"
    return answer

In [134]:
def solution(num):
    count = 0
    if num == 1:
        return 0
    while count <= 500:
        if num % 2 == 0:
            num = num / 2
            count += 1
            if num == 1:
                break
        else:
            num = num * 3 + 1
            count += 1
    if count > 500:
        count = -1
    return count

solution(1)

0

In [10]:
def solution(d, budget):
    answer = 0
    if sum(d) <= budget:
        return len(d)
    else:
        while True:
            d.remove(max(d))
            if sum(d) <= budget:
                break

    return len(d)

solution([1,3,2,5,4], 9)

3

In [6]:
d = [1,2,3,4,5]
d.remove(max(d))
d

[1, 2, 3, 4]

In [35]:
def solution(x):
    a = str(x)
    tmp = list(a)
    b = 0
    for i in tmp:
        b += int(i)
    if (x / b) / int(x / b) == 1:
        return True
    else:
        return False

solution(10)


True

In [30]:
x = 123
b = 0
a = str(x)
tmp = list(a)
for i in tmp:
    b += int(i)

b

(12 / b) / int(12/b)

1.0

In [52]:
a = "123456789"
a[-4:]
a[:-4]

'12345'

In [ ]:
def solution(phone_number):
    return ("*" * len(phone_number[:-4])) + phone_number[-4:]


In [68]:
def solution(arr1, arr2):
    tmp_in = []
    answer = []
    for i, j in arr1, arr2:
        for a, b in i, j:
            tmp_in.append(a + b)
        answer.append(tmp_in)
        tmp_in = []

    return answer

solution([[1,2],[2,3]],	[[3,4],[5,6]])

KeyboardInterrupt: 

In [73]:
arr1 = [[1,2],[2,3], [1,2],[2,3]]
arr2 = [[3,4],[5,6], [1,2],[2,3]]	

for i in arr1, arr2:
    print(i)


[[1, 2], [2, 3], [1, 2], [2, 3]]
[[3, 4], [5, 6], [1, 2], [2, 3]]


In [79]:
def solution(arr1, arr2):
    tmp_in = []
    answer = []
    for i in range(len(arr1)):
        for j in range(len(arr1[i])):
            tmp_in.append(arr1[i][j] + arr2[i][j])
        answer.append(tmp_in)
        tmp_in = []

    return answer

solution([[1,2],[2,3]],	[[3,4],[5,6]])

[[4, 6], [7, 9]]

In [ ]:
def solution(x, n):
    x_1 = x
    answer = [x]
    for i in range(n-1):
        x += x_1
        answer.append(x)
    return answer

In [80]:
a, b = map(int, input().strip().split(' '))
print(a + b)

21


In [84]:
a, b = map(int, input().strip().split(' '))
for i in range(b):
    for j in range(a):
        print("*", end = "")
    print("")


*****
*****
*****


'0b11110'

In [ ]:
def solution(n, arr1, arr2):
    answer = []
    tmp = "0" * n
    

    return answer

In [89]:
bin(46)

'0b101110'

In [90]:
bin(27)

'0b11011'

In [92]:
bin(46 * 27)

'0b10011011010'

In [ ]:
def solution(s):
    if len(s) == 4 or len(s) == 6:
        if s.isdigit():
            return True
    return False

In [96]:
a = "123a4"
a.isdigit()

False

In [ ]:
def solution(s):
    if s.isdigit():
        return int(s)
    else:
        if s[0] == "+":
            return int(s[1:])
        else:
            return -1 * int(s[1:])

In [97]:
def solution(x):
    answer = 0
    for i in range(1, x + 1):
        if (x / i) / int(x / i) == 1:
            answer += i
    return answer
        
solution(10)


18

In [103]:
def solution(n, m):
    tmp_min_n, tmp_min_m, tmp_max, tmp = [], [], [], []
    answer = []
  
    for i in range(1, n + 1):
        if (n / i) / int(n / i) == 1:
            tmp_min_n.append(i)

    for i in range(1, m + 1):
        if (m / i) / int(m / i) == 1:
            tmp_min_m.append(i)

    for i in tmp_min_n:
        if i in tmp_min_m:
            tmp.append(i)
    answer.append(max(tmp))
    answer.append(int(n * m / answer[0]))
    
    return answer
solution(2, 5)

[1, 10.0]

In [122]:
def solution(priorities, location):
    answer = 0
    for i in range(priorities[location] + 1 , max(priorities) + 1):
        answer += priorities.count(i)

    for i in priorities[location+1:]:
        if i == priorities[location]:
            answer += 1

    return answer

solution([1, 1, 9, 1, 1, 1], 0)

5

In [114]:
a = [1,2,3,2,4,4,5,6,4,4,34,5,6]
b = 2
type(a[b])


int

In [139]:
def solution(priorities, location):
    c = 0
    while c != len(priorities):
        for i in priorities:
            if i != max(priorities):
                priorities.remove(i)
                priorities.append(i)
                location -= 1
                if location == -1:
                    location = len(priorities)
            else:
                if priorities.index(i) == location:
                    c += 1
                    return c
                else:
                    priorities.remove(i)
                    c += 1

solution([2, 1, 3, 2], 2)    

Error: connect ECONNREFUSED 127.0.0.1:51795

In [129]:
a = [1, 1, 9, 1, 9, 1, 1]
a.remove(9)
a.index(1)

0

In [ ]:
def solution(priorities, location):
    c = 0
    while c != len(priorities):
        for i in priorities:
            if i != max(priorities):
                priorities.remove(i)
                priorities.append(i)
                location -= 1
                if location == -1:
                    location = len(priorities)
            else:
                if priorities.index(i) == location:
                    c += 1
                    return c
                else:
                    priorities.remove(i)
                    c += 1
    return c

print(solution(	[1, 1, 9, 1, 1, 1], 0))

Error: connect ECONNREFUSED 127.0.0.1:51795

In [140]:
a = [1, 1, 1, 1, 1]
max(a)

1

In [ ]:
def solution(s):

In [161]:
a = []
s = "try hello world"
a = s.split().copy()
answer = " ".join(map(str, a))
answer

'try hello world'

In [152]:
def solution(s):
    a = []
    a = s.split().copy()
    tmp = ""
    tmp_2 = []
    answer = ""

    for i in a:
        for j in range(len(i)):
            if j % 2 == 0:
                tmp = tmp + i[j].upper()
            else:
                tmp = tmp + i[j].lower()
        tmp_2.append(tmp)
        tmp = ""
    answer = " ".join(map(str, tmp_2))
    return answer

'TrY HeLlO WoRlD'

In [ ]:
def solution(s):
    answer = ''
    c = 0
    for i in s:
        if i!=' ':
            if c%2==0:
                answer += i.upper()
            else:
                answer += i.lower()
            c += 1
        else:
            answer += i
            c=0

    return answer

In [162]:
a = "123"
" ".join(a)

'1 2 3'

In [ ]:
def solution_1(m):
    answer = 1
    chk = 0
    for i in range(1, m + 1, 2):
        for j in range(1, int(i**0.5) + 1, 2):
            if i % j == 0:
                chk += 1
                if chk >2:
                    continue
        if chk == 2:
            answer += 1
        chk = 0
    return answer

In [163]:
def prime_list(n):
    # 에라토스테네스의 체 초기화: n개 요소에 True 설정(소수로 간주)
    sieve = [True] * n

    # n의 최대 약수가 sqrt(n) 이하이므로 i=sqrt(n)까지 검사
    m = int(n ** 0.5)
    for i in range(2, m + 1):
        if sieve[i] == True:           # i가 소수인 경우
            for j in range(i+i, n, i): # i이후 i의 배수들을 False 판정
                sieve[j] = False

    # 소수 목록 산출
    return len([i for i in range(2, n) if sieve[i] == True])

In [188]:
def solution(n):
    sieve = [True] * n
    m = int(n ** 0.5)
    for i in range(2, m + 1):
        if sieve[i] == True:           
            for j in range(i+i, n, i): 
                sieve[j] = False


    return len([i for i in range(2, n) if sieve[i] == True])
solution(100000000)

5761455

In [183]:
def solution_1(m):
    answer = 1
    chk = 0
    for i in range(1, m + 1, 2):
        for j in range(1, i + 1):
            if i % j == 0:
                chk += 1
                if chk >2:
                    continue
                else:
                    pass
        if chk == 2:
            answer += 1
        chk = 0
    return answer
solution_1(100000)

KeyboardInterrupt: 

In [191]:
def make_3(n):
    q = n // 3
    r = str(n % 3)
    
    if q == 0:
        return r
    else:
        return make_3(q) + r

int('101', 3)

10

In [ ]:
def make_3(n):
    q = n // 3
    r = str(n % 3)
    
    if q == 0:
        return r
    else:
        return make_3(q) + r

def solution(n):
    tmp_2 = ""
    tmp = list(make_3(n))
    for i in range(len(tmp)):
        tmp_2 += tmp.pop()

    
    return int(tmp_2, 3)

In [193]:
def solution(w,h):
    return w*h - (min(w,h) * (int(max(w,h)/min(w,h)) + 1))

2

In [ ]:
def solution(prices):
    answer = []
    c1 = 1
    c2 = 0
    for i in prices:
        for j in prices[c1:]:
            if i >= j:
                c2 += 1
            else:
                answer.append(c2)
                c2 = 0
                c1 += 1
                break
        answer.append(c2)
        c2 = 0
        c1 += 1
    return answer

In [ ]:
def solution(prices):

    for i in prices:
        

In [ ]:
def solution(numbers):
    answer = ''
    tmp = numbers.copy()
    

    return answer

In [17]:
import itertools

numbers = [3, 30, 34, 5, 9]
tmp = []
numbers = list(map(str, numbers))

tmp.append((''.join, itertools.permutations(numbers, len(numbers))))

tmp

[(<function str.join(iterable, /)>, <itertools.permutations at 0x22aade25a90>)]

In [15]:
numbers = [3, 30, 34, 5, 9]
tmp = []
numbers = map(str, numbers)

print(list(numbers))

['3', '30', '34', '5', '9']


In [19]:
def perm(inData, i):

    if i == len(inData) - 1:

        print(inData)

    else:

        for j in range(i, len(inData)):

            inData[i], inData[j] = inData[j], inData[i]

            perm(inData, i+1)

            inData[i], inData[j] = inData[j], inData[i]

perm(['A', 'B', 'C'], 2)

['A', 'B', 'C']


In [ ]:
import itertools

numbers = [3, 30, 34, 5, 9]

list(itertools.permutations(numbers))

In [29]:
from itertools import permutations


def solution(numbers):
    tmp = list(permutations(numbers))
    #tmp = list(map(str, tmp))
    tmp_num = []
    for i in tmp:
        tmp_num.append((''.joina(list(i)))

    print(tmp_num)


    #return max(tmp_num)


solution([3, 30, 34, 5, 9])

SyntaxError: invalid syntax (<ipython-input-29-1f36a2f794ca>, line 11)

In [41]:
from itertools import permutations

tmp = list(permutations([3, 30, 34, 5, 9]))
print(type(tmp[0]))

a = list(tmp[0])
a = list(map(str, a))
print(a)

print(type(''.join(a)))
# tmp_num = []
# for i in tmp:
#     tmp_num.append((''.joina(list(i)))





<class 'tuple'>
['3', '30', '34', '5', '9']
<class 'str'>


In [54]:
from itertools import permutations

def solution(numbers):
    tmp_1, tmp_2, tmp_3, tmp_4 = [], [], [], []

    tmp_1 = list(permutations(numbers))
    for i in tmp_1:
        tmp_2.append(list(map(str, list(i))))
    
    for i in tmp_2:
        tmp_3.append(''.join(i))

    for i in tmp_3:
        tmp_4.append(int(i))
    
    return str(max(tmp_4))
    

solution([3, 30, 34, 5, 9,23,4,345,356,456,345,345,63,34,534,435,6])


'9534330'

In [61]:
a = [3, 30, 34, 5, 9,23,4,345,356,456,345,345,63,34,534,435,6]
a.pop(0)
a.insert(0, 1)
a.append(1)
a

[1, 30, 34, 5, 9, 23, 4, 345, 356, 456, 345, 345, 63, 34, 534, 435, 6, 1]

In [70]:
a = [1, 2, 3] #리스트는 객체다.
b = a
c = a.copy()

print('a == b', a == b)
print('a == c', a == c)
print('a is b', a is b) # 객체비교는 is
print('a is c', a is c)

a == b True
a == c True
a is b True
a is c False


In [72]:
0.2 * 3

0.6000000000000001

In [73]:
1.1.as_integer_ratio()

(2476979795053773, 2251799813685248)

In [74]:
2476979795053773 /  2251799813685248

1.1

In [75]:
2.75.as_integer_ratio()

(11, 4)

In [76]:
from fractions import Fraction


def rounding_floats(number1, places):
    return round(number1, places)


def float_to_fractions(number):
    return Fraction(*number.as_integer_ratio())


def get_denominator(number1, number2):
    """ 분모를 반환한다."""
    a = Fraction(number1, number2)
    return a.denominator


def get_numerator(number1, number2):
    """ 분자를 반환한다."""
    a = Fraction(number1, number2)
    return a.numerator


def test_testing_floats():
    number1 = 1.25
    number2 = 1
    number3 = -1
    number4 = 5/4
    number6 = 6
    assert(rounding_floats(number1, number2) == 1.2)
    assert(rounding_floats(number1*10, number3) == 10)
    assert(float_to_fractions(number1) == number4)
    assert(get_denominator(number2, number6) == number6)
    assert(get_numerator(number2, number6) == number2)
    print("테스트 통과!")


if __name__ == "__main__":
    test_testing_floats()

테스트 통과!


In [85]:
def convert_to_decimal(number, base):
    multiplier, result = 1, 0
    while number > 0:
        result += number % 10 * multiplier
        multiplier *= base
        number = number // 10
    return result


In [84]:
convert_to_decimal(100000000000000000000, 2)

1048576

In [87]:
def convert_from_decimal(number, base):
    multiplier, result = 1, 0
    while number > 0:
        result += number % base * multiplier
        multiplier *= 10
        number = number // base
    return result

In [90]:
convert_from_decimal(10, 2) - 1

1009

In [91]:
def convert_dec_to_any_base_rec(number, base):
    convertString = "012345679ABCDEF"
    if number < base:
        return convertString[number]
    else:
        return convert_dec_to_any_base_rec(number // base, base) \
            + convertString[number % base]

In [ ]:
convert_dec_to_any_base_rec(2, 3)

In [30]:
def finding_gcd(a, b):
    while(b != 0):
        r, a, b = b, b, a%b; return r

finding_gcd(4, 12541216)

12541216

In [6]:
finding_gcd(5, 10)

5

In [13]:
10%5

0

In [ ]:
Hello World!

In [16]:
a, b = map(int, input().split())

print(a, b)

1 3


In [ ]:
import math


def find_fibonacci_seq_iter(n):
    if n < 2:
        return n
    a, b = 0, 1
    for i in range(n):
        a, b = b, a + b
    return a


def find_fibonacci_seq_rec(n):
    if n < 2:
        return n
    return find_fibonacci_seq_rec(n - 1) + find_fibonacci_seq_rec(n - 2)


def find_fibonacci_seq_form(n):
    sq5 = math.sqrt(5)
    phi = (1 + sq5) / 2
    return int(math.floor(phi ** n / sq5))

In [37]:
def finding_prime(number):
    num = abs(number)
    if num < 4:
        return True
    for x in range(2, num):
        if num % x == 0:
            return False
    return True

In [39]:
finding_prime(17)

True

In [43]:
import numpy as np


def testing_numpy():
    ax = np.array([1, 2, 3])
    ay = np.array([3, 4, 5])
    print("1\n",ax)
    print("2\n",ax*2)
    print("3\n",ax+10)
    print("4\n",np.sqrt(ax))
    print("5\n",np.cos(ax))
    print("6\n",ax-ay)
    print("7\n",np.where(ax < 2, ax, 10))

    m = np.matrix([ax, ay, ax])
    print(m)
    print(m.T)

    grid1 = np.zeros(shape=(10, 10), dtype=float)
    grid2 = np.ones(shape=(10, 10), dtype=float)
    print(grid1)
    print(grid2)
    print(grid1[1]+10)
    print(grid2[:, 2]*2)


if __name__ == "__main__":
    testing_numpy()

1
 [1 2 3]
2
 [2 4 6]
3
 [11 12 13]
4
 [1.         1.41421356 1.73205081]
5
 [ 0.54030231 -0.41614684 -0.9899925 ]
6
 [-2 -2 -2]
7
 [ 1 10 10]
[[1 2 3]
 [3 4 5]
 [1 2 3]]
[[1 3 1]
 [2 4 2]
 [3 5 3]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [44]:
  
import numpy
import time


def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1


def numpy_version():
    t1 = time.time()
    X = numpy.arange(10000000)
    Y = numpy.arange(10000000)
    Z = X + Y
    return time.time() - t1


if __name__ == "__main__":
    print(trad_version())
    print(numpy_version())

2.3136963844299316
0.045888423919677734


In [51]:
p = range(10)

print(type(p))

for i in p:
    print(i)

<class 'range'>
0
1
2
3
4
5
6
7
8
9


In [57]:
import copy

a = [1, 2]
b = a
c = copy.deepcopy(a)

a.append(3)


print(a, b, c)

[1, 2, 3] [1, 2, 3] [1, 2]


In [70]:
print('\u0022 \u0022')

" "


In [76]:
a = ['12', '34']

b = "".join(a)

print(b)

1234


In [77]:
def func(*args):
      print(args)
      print(type(args))

In [92]:

func(1,2,3,12,2,32,23,23,23)

(1, 2, 3, 12, 2, 32, 23, 23, 23)
<class 'tuple'>


In [97]:
import numpy as np
import pandas as pd
import math

a = [1,2,3,2,3]

a.mean()

AttributeError: 'list' object has no attribute 'mean'

In [98]:
def func(**kwargs):
      print(args)
      print(type(args))

In [123]:
func(a = 2)

{'a': 2}
<class 'dict'>


In [119]:
a = {1:2, 2:4}
func({1:2})

TypeError: func() takes 0 positional arguments but 1 was given

In [111]:
a = {1:2, 2:4}
a

{1: 2, 2: 4}

In [133]:
def sum(a, b, c):
    return a + b + c

numbers = [1, 2, 3]
#sum(numbers) # error

print(sum(*numbers)) # 출력 : 6
print(*{'가', '나', '다'})
print(*{"a", "b", "c"})

6
나 가 다
b a c


In [129]:
a = [1, 2, 3]
print(a)
print(*a)
print(*"asd")

[1, 2, 3]
1 2 3
a s d


In [176]:
count = 0
profit = 1
while count < 240:
    count += 1
    profit = 1.05 * profit
    # print("%3d일차 수익률 : %3.2f" %(count, 100 * profit - 100) + "%")
print("%3d일차 수익률 : %3.2f" %(count, profit))


240일차 수익률 : 121739.57


In [179]:
a = '1231321'
a.strip("1")
a.strip("1")

'23132'

In [180]:
import string
import sys


def count_unique_word():
    words = {}
    strip = string.whitespace + string.punctuation + string.digits + "\"'"
    for filename in sys.argv[1:]:
        with open(filename) as file:
            for line in file:
                for word in line.lower().split():
                    word = word.strip(strip)
                    if len(word) > 2:
                        words[word] = words.get(word, 0) + 1

    for word in sorted(words):
        print("'{0}': {1}번".format(word, words[word]))


if __name__ == "__main__":
    count_unique_word()

FileNotFoundError: [Errno 2] No such file or directory: '--ip=127.0.0.1'

In [190]:
import string

words = {}
line = '''import string

words = {}
line = 'wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd'

strip = string.whitespace + string.punctuation + string.digits + "\"'"

for word in line.lower().split():
                    word = word.strip(strip)
                    if len(word) > 2:
                        words[word] = words.get(word, 0) + 1

for word in sorted(words):
    print("'{0}': {1}번".format(word, words[word]))'''

strip = string.whitespace + string.punctuation + string.digits + "\"'"

for word in line.lower().split():
                    word = word.strip(strip)
                    if len(word) > 2:
                        words[word] = words.get(word, 0) + 1

for word in sorted(words):
    print("'{0}': {1}번".format(word, words[word]))

'asd': 53번
'for': 2번
'import': 1번
'len(word': 1번
'line': 1번
'line.lower().split': 1번
'print': 1번
'sorted(words': 1번
'string': 1번
'string.digits': 1번
'string.punctuation': 1번
'string.whitespace': 1번
'strip': 1번
'word': 3번
'word.strip(strip': 1번
'words': 1번
'words.get(word': 1번
'words[word': 2번
'wow': 62번
'번".format(word': 1번


In [184]:
line = 'wow chingoodle BackBack-e a-jeocciya'
type(line.lower().split())

list

In [ ]:
'''import string

words = {}
line = 'wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow wow asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd asd'

strip = string.whitespace + string.punctuation + string.digits + "\"'"

for word in line.lower().split():
                    word = word.strip(strip)
                    if len(word) > 2:
                        words[word] = words.get(word, 0) + 1

for word in sorted(words):
    print("'{0}': {1}번".format(word, words[word]))'''

In [197]:
a = "01234567890123456789"
a.index('1', a.index('1', 0 , 20)+1 , 20)
a.count('1', 0, -1)

2

In [202]:
a = "wow"
f"we can write {a!r}"

"we can write 'wow'"

In [205]:
a = 'a', 'b'
type(a)
print(a)

('a', 'b')


In [210]:
*x, y = (1, 2, 3, 4)
print(x, y)

[1, 2, 3] 4


In [239]:
a = []
a.append("wow")
a
a.extend("wow")
a
a += "wpow"
a
a.insert( len(a) ,"a")
a
a.index("o")
a.sort()
a.reverse()
a[::-1]


one, *last = a
print(one, last)

wow ['w', 'w', 'w', 'w', 'p', 'o', 'o', 'a']


In [236]:
a = ['1', '2']
q, w = a
q;w

'2'

In [ ]:
def solution(phone_book):
    tmp = []
    a = min(map(len, phone_book))
    while True:
        for i in phone_book:
            if len(i) == a:
                tmp.append(i)
                phone_book.remove(i)
        for j in tmp:
            for k in phone_book:
                if j == k[:a]:
                    return False
        
        if phone_book == []:
            return True

solution(["113", "44", "4544"])


In [250]:
a = ['12','123','1235','567','88']
tmp = []
min(map(len, a))
for i in a:
    if len(i) == min(map(len, a)):
        tmp.append(i)
        a.remove(i)
for j in tmp:
    for k in a:
        if j in k:
            print(True)

a

True
True


['123', '1235', '567']

In [266]:
a = "12345"
b = a[:2]
b

'12'

In [271]:
def solution(phone_book):
    tmp = [] 
    while True:
        for i in phone_book:
            if len(i) == min(map(len, phone_book)):
                tmp.append(i)
                phone_book.remove(i)
        for j in tmp:
            for k in phone_book:
                if j == k[:len(j)]:
                    return False
        
        if phone_book == []:
            return True

solution(["113", "44", "4544"])


True